# Generated by Django 5.1.1 on 2024-10-06 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_catalog', '0002_alter_sections_options_sections_desc_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='elements',
            options={'verbose_name': 'Элемент', 'verbose_name_plural': 'Элементы'},
        ),
        migrations.AlterField(
            model_name='elements',
            name='nick',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
