# Generated by Django 5.1.1 on 2024-10-06 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_catalog', '0004_alter_elements_nick_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elements',
            name='nick',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
