# Generated by Django 5.1.1 on 2024-10-06 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_catalog', '0005_alter_elements_nick'),
    ]

    operations = [
        migrations.AddField(
            model_name='elements',
            name='vk_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
