# Generated by Django 5.1.1 on 2024-10-08 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_catalog', '0006_elements_vk_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sections',
            name='sort',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
