# Generated by Django 5.1.1 on 2024-10-08 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_catalog', '0007_sections_sort'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sections',
            name='sort',
        ),
    ]
