# Generated by Django 5.1.1 on 2024-10-08 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_catalog', '0008_remove_sections_sort'),
    ]

    operations = [
        migrations.AddField(
            model_name='sections',
            name='sort',
            field=models.IntegerField(default=0),
        ),
    ]
