# Generated by Django 5.1.1 on 2024-10-10 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_catalog', '0009_sections_sort'),
    ]

    operations = [
        migrations.AddField(
            model_name='elements',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
