# Generated by Django 5.1.1 on 2024-10-12 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_catalog', '0010_elements_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Step3FreezingElements',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
