# Generated by Django 5.1.1 on 2024-10-12 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_catalog', '0011_step3freezingelements'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Step3FreezingElements',
        ),
    ]
