# Generated by Django 5.1.1 on 2024-10-12 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_catalog', '0013_step3freezingelements'),
    ]

    operations = [
        migrations.RenameField(
            model_name='step3freezingelements',
            old_name='id',
            new_name='el_id',
        ),
    ]
