# Generated by Django 5.1.1 on 2024-10-13 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_catalog', '0014_rename_id_step3freezingelements_el_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Step3FreezingElements',
        ),
    ]
