# Generated by Django 5.1.1 on 2024-10-15 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_catalog', '0015_delete_step3freezingelements'),
    ]

    operations = [
        migrations.AddField(
            model_name='elements',
            name='step1',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
