# Generated by Django 5.1.1 on 2024-10-15 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_catalog', '0017_elements_step2_continue_elements_step2_good_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elements',
            name='step2_continue',
        ),
    ]
