# Generated by Django 5.1.1 on 2024-10-15 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_catalog', '0018_remove_elements_step2_continue'),
    ]

    operations = [
        migrations.AddField(
            model_name='elements',
            name='step2_continue',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
