# Generated by Django 5.1.1 on 2024-10-15 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_catalog', '0019_elements_step2_continue'),
    ]

    operations = [
        migrations.AddField(
            model_name='elements',
            name='step3_parsed',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
