# Generated by Django 5.1.1 on 2024-10-26 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_catalog', '0020_elements_step3_parsed'),
    ]

    operations = [
        migrations.AddField(
            model_name='elements',
            name='time_last_active',
            field=models.DateTimeField(null=True),
        ),
    ]
