# Generated by Django 5.1.1 on 2024-10-13 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_catalog', '0015_delete_step3freezingelements'),
        ('app_main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Step3FreezingElements',
            fields=[
                ('el_id', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app_catalog.elements')),
                ('chrome', models.CharField(db_index=True, max_length=32, unique=True)),
            ],
        ),
    ]
