# Generated by Django 5.1.1 on 2024-10-13 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0002_step3freezingelements'),
    ]

    operations = [
        migrations.RenameField(
            model_name='step3freezingelements',
            old_name='el_id',
            new_name='elements',
        ),
    ]
