# Generated by Django 5.1.1 on 2024-10-13 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0003_rename_el_id_step3freezingelements_elements'),
    ]

    operations = [
        migrations.RenameField(
            model_name='step3freezingelements',
            old_name='chrome',
            new_name='process_code',
        ),
    ]
