# Generated by Django 5.1.1 on 2024-10-14 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0006_pipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debug',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.FloatField()),
                ('value', models.TextField()),
            ],
        ),
    ]
