# Generated by Django 5.1.1 on 2024-10-16 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0007_debug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step2freezingelements',
            name='process_code',
            field=models.CharField(db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='step3freezingelements',
            name='process_code',
            field=models.CharField(db_index=True, max_length=32),
        ),
    ]
