# Generated by Django 5.1.1 on 2024-10-16 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0008_alter_step2freezingelements_process_code_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pipe',
        ),
    ]
